In [28]:
import pandas as pd
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df=pd.read_csv('data/dulieuxettuyendaihoc.csv', header=0,delimiter=',', encoding='utf-8')
df

,MSSV,T1,T2,T3,T4,T5,T6,GT,DT,KV,NGONNGU,TOANLOGICPHANTICH,GIAIQUYETVANDE,KT,NGAYTHI,DINHHUONGNGHENGHIEP
0,SV001,7.2,8.4,7.4,7.2,7.4,6.9,F,NaN,2NT,3.25,3.25,4.50,A1,12/7/2018,No
1,SV002,5.4,6.3,4.3,4.9,3.0,4.0,M,NaN,1,6.00,4.00,3.50,C,12/7/2018,Yes
2,SV003,5.6,5.0,2.8,6.1,4.8,5.7,M,NaN,1,5.00,6.75,4.00,C,12/7/2018,No
3,SV004,6.6,5.1,5.9,4.1,6.1,7.4,M,NaN,1,4.25,4.25,5.25,D1,12/7/2018,No
4,SV005,6.0,5.4,7.6,4.4,6.8,8.0,M,NaN,2NT,4.25,4.50,5.00,A,12/7/2018,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,SV0096,8.6,8.9,7.7,6.7,7.9,6.6,F,NaN,1,5.25,1.50,6.25,C,7/20/2022,Yes
96,SV0097,3.7,4.1,3.1,3.4,5.5,5.7,F,NaN,1,5.25,3.75,4.75,C,7/20/2022,No
97,SV0098,8.8,9.5,9.5,8.5,9.0,8.5,M,NaN,2NT,7.00,8.00,4.00,C,7/20/2022,Yes
98,SV0099,2.7,2.8,6.2,5.2,4.1,4.3,M,NaN,1,5.00,3.50,5.50,C,7/20/2022,No
99,SV00100,4.1,4.4,6.0,4.3,5.6,5.1,M,NaN,2NT,5.25,2.50,4.25,C,7/20/2022,Yes

In [29]:
df.head(10)

,MSSV,T1,T2,T3,T4,T5,T6,GT,DT,KV,NGONNGU,TOANLOGICPHANTICH,GIAIQUYETVANDE,KT,NGAYTHI,DINHHUONGNGHENGHIEP
0,SV001,7.2,8.4,7.4,7.2,7.4,6.9,F,NaN,2NT,3.25,3.25,4.50,A1,12/7/2018,No
1,SV002,5.4,6.3,4.3,4.9,3.0,4.0,M,NaN,1,6.00,4.00,3.50,C,12/7/2018,Yes
2,SV003,5.6,5.0,2.8,6.1,4.8,5.7,M,NaN,1,5.00,6.75,4.00,C,12/7/2018,No
3,SV004,6.6,5.1,5.9,4.1,6.1,7.4,M,NaN,1,4.25,4.25,5.25,D1,12/7/2018,No
4,SV005,6.0,5.4,7.6,4.4,6.8,8.0,M,NaN,2NT,4.25,4.50,5.00,A,12/7/2018,No
5,SV006,9.3,9.6,7.1,8.5,8.5,7.8,M,NaN,1,1.50,4.00,6.00,D1,12/7/2018,No
6,SV007,2.8,4.4,4.6,4.7,5.4,5.3,F,NaN,2,6.50,6.75,5.25,C,12/7/2018,Yes
7,SV008,8.3,6.7,8.6,8.3,8.5,8.3,F,NaN,2,3.75,4.50,4.25,D1,12/7/2018,Yes
8,SV009,6.5,7.3,6.4,8.1,7.7,7.7,F,NaN,1,3.50,3.50,6.75,D1,12/7/2018,Yes
9,SV0010,7.3,8.0,6.5,5.5,7.5,6.9,F,NaN,1,4.00,4.75,5.50,D1,12/7/2018,Yes

In [30]:
#Ä‘á»•i tÃªn
df.rename(columns={'TOANLOGICPHANTICH':'LOGIC',
                   'GIAIQUYETVANDE':'UNGXU',
                   'DINHHUONGNGHENGHIEP':'HUONGNGHIEP'}, 
                   inplace=True)
df

,MSSV,T1,T2,T3,T4,T5,T6,GT,DT,KV,NGONNGU,LOGIC,UNGXU,KT,NGAYTHI,HUONGNGHIEP
0,SV001,7.2,8.4,7.4,7.2,7.4,6.9,F,NaN,2NT,3.25,3.25,4.50,A1,12/7/2018,No
1,SV002,5.4,6.3,4.3,4.9,3.0,4.0,M,NaN,1,6.00,4.00,3.50,C,12/7/2018,Yes
2,SV003,5.6,5.0,2.8,6.1,4.8,5.7,M,NaN,1,5.00,6.75,4.00,C,12/7/2018,No
3,SV004,6.6,5.1,5.9,4.1,6.1,7.4,M,NaN,1,4.25,4.25,5.25,D1,12/7/2018,No
4,SV005,6.0,5.4,7.6,4.4,6.8,8.0,M,NaN,2NT,4.25,4.50,5.00,A,12/7/2018,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,SV0096,8.6,8.9,7.7,6.7,7.9,6.6,F,NaN,1,5.25,1.50,6.25,C,7/20/2022,Yes
96,SV0097,3.7,4.1,3.1,3.4,5.5,5.7,F,NaN,1,5.25,3.75,4.75,C,7/20/2022,No
97,SV0098,8.8,9.5,9.5,8.5,9.0,8.5,M,NaN,2NT,7.00,8.00,4.00,C,7/20/2022,Yes
98,SV0099,2.7,2.8,6.2,5.2,4.1,4.3,M,NaN,1,5.00,3.50,5.50,C,7/20/2022,No
99,SV00100,4.1,4.4,6.0,4.3,5.6,5.1,M,NaN,2NT,5.25,2.50,4.25,C,7/20/2022,Yes

In [31]:
df.groupby('LOGIC')[['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'GT']].describe()

         T1                                                      T2            \
      count      mean       std  min    25%   50%    75%  max count      mean
LOGIC
1.50    1.0  8.600000       NaN  8.6  8.600  8.60  8.600  8.6   1.0  8.900000
2.00    1.0  3.600000       NaN  3.6  3.600  3.60  3.600  3.6   1.0  4.200000
2.25    2.0  4.550000  3.040559  2.4  3.475  4.55  5.625  6.7   2.0  4.950000
2.50    2.0  4.950000  1.202082  4.1  4.525  4.95  5.375  5.8   2.0  5.400000
2.75    2.0  5.650000  1.060660  4.9  5.275  5.65  6.025  6.4   2.0  5.200000
3.00    3.0  3.966667  1.305118  2.5  3.450  4.40  4.700  5.0   3.0  5.466667
3.25    2.0  6.600000  0.848528  6.0  6.300  6.60  6.900  7.2   2.0  7.850000
3.50   15.0  6.106667  1.501650  2.7  5.150  6.50  7.250  8.2  15.0  6.606667
3.75    7.0  4.985714  1.386156  3.0  4.100  5.30  5.650  7.1   7.0  5.542857
4.00   15.0  6.426667  1.732243  3.6  5.200  6.10  8.000  9.3  15.0  6.673333
4.25    2.0  5.900000  0.989949  5.2  5.550  5.90  6.250  6.6   2.0  5.950000
4.50   19.0  6.247368  1.317982  4.6  5.250  5.80  7.200  8.4  19.0  6.378947
4.75    8.0  5.800000  2.036804  2.6  4.950  6.10  7.425  7.9   8.0  6.637500
5.00    3.0  6.166667  2.119748  3.9  5.200  6.50  7.300  8.1   3.0  5.100000
5.25    6.0  5.333333  1.111156  3.4  5.075  5.40  6.100  6.5   6.0  6.700000
5.50    4.0  6.025000  0.970824  4.9  5.500  6.00  6.525  7.2   4.0  6.500000
5.75    1.0  7.200000       NaN  7.2  7.200  7.20  7.200  7.2   1.0  7.900000
6.00    2.0  6.200000  1.555635  5.1  5.650  6.20  6.750  7.3   2.0  6.550000
6.50    2.0  7.900000  0.000000  7.9  7.900  7.90  7.900  7.9   2.0  7.750000
6.75    2.0  4.200000  1.979899  2.8  3.500  4.20  4.900  5.6   2.0  4.700000
8.00    1.0  8.800000       NaN  8.8  8.800  8.80  8.800  8.8   1.0  9.500000

       ...     T5         T6
       ...    75%  max count      mean       std  min    25%   50%    75%  max
LOGIC  ...
1.50   ...  7.900  7.9   1.0  6.600000       NaN  6.6  6.600  6.60  6.600  6.6
2.00   ...  5.800  5.8   1.0  3.700000       NaN  3.7  3.700  3.70  3.700  3.7
2.25   ...  5.675  6.1   2.0  5.150000  1.909188  3.8  4.475  5.15  5.825  6.5
2.50   ...  6.875  7.3   2.0  5.900000  1.131371  5.1  5.500  5.90  6.300  6.7
2.75   ...  6.725  6.8   2.0  7.200000  0.424264  6.9  7.050  7.20  7.350  7.5
3.00   ...  6.300  6.8   3.0  5.533333  0.251661  5.3  5.400  5.50  5.650  5.8
3.25   ...  7.625  7.7   2.0  6.700000  0.282843  6.5  6.600  6.70  6.800  6.9
3.50   ...  7.850  8.7  15.0  6.640000  1.711223  4.0  5.700  6.60  7.900  9.3
3.75   ...  6.650  6.9   7.0  6.271429  0.914174  5.1  5.650  6.10  6.950  7.5
4.00   ...  7.750  8.9  15.0  7.080000  1.304498  4.0  6.600  7.50  7.800  8.9
4.25   ...  7.000  7.3   2.0  7.350000  0.070711  7.3  7.325  7.35  7.375  7.4
4.50   ...  8.100  9.3  19.0  7.278947  1.029336  5.2  6.750  7.30  8.250  8.6
4.75   ...  7.775  9.5   8.0  8.150000  1.299450  5.7  7.725  8.35  9.100  9.5
5.00   ...  8.200  9.3   3.0  6.966667  1.401190  5.6  6.250  6.90  7.650  8.4
5.25   ...  7.775  8.3   6.0  6.883333  1.739444  3.7  6.450  7.60  7.850  8.4
5.50   ...  7.975  8.5   4.0  7.200000  1.061446  6.4  6.475  6.85  7.575  8.7
5.75   ...  7.800  7.8   1.0  6.900000       NaN  6.9  6.900  6.90  6.900  6.9
6.00   ...  8.000  8.4   2.0  7.700000  0.565685  7.3  7.500  7.70  7.900  8.1
6.50   ...  8.450  8.6   2.0  8.100000  0.000000  8.1  8.100  8.10  8.100  8.1
6.75   ...  5.250  5.4   2.0  5.500000  0.282843  5.3  5.400  5.50  5.600  5.7
8.00   ...  9.000  9.0   1.0  8.500000       NaN  8.5  8.500  8.50  8.500  8.5

[21 rows x 48 columns]

In [32]:
X= df[['T1', 'T2', 'T3', 'T4', 'T5', 'T6','GT']].values #input
y= df[['LOGIC']].values #output

In [33]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X,y,test_size=0.2, random_state=16)

In [34]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler()
X = sc.fit_transform(X)

ValueError: could not convert string to float: 'F'